spring:
  application:
    name: serie-service
  data:
    mongodb:
    host: localhost
    port: 27017
    database: series
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

server:
  port: 8082

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true


queue:
  serie:
    name: SerieQueue