spring:
  application:
    name: serie-service
  data:
    mongodb:
      database: test
#falta lo de mongo

server:
  port: 8082

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true